spring:
  datasource:
    url: jdbc:mysql://localhost:3306/matzipcurator?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 50
        default_batch_fetch_size: 100  # 연관 엔티티 지연 로딩 시 배치 페치 사이즈
    open-in-view: false  # OSIV 비활성화
    defer-datasource-initialization: true # hibernate가 스키마 초기화 후 SQL스크립트 실행

  data:
    redis:
      host: localhost
      port: 6379
    elasticsearch:
      cluster-nodes: localhost:9200
      cluster-name: es-docker-cluster
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      group-id: matzipcurator-group
      auto-offset-reset: earliest

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.elasticsearch.client.WIRE: TRACE

server:
  port: 8080

jwt:
  secret: your-secret-key-here-should-be-very-long-and-secure
  expiration: 86400000  # 24 hours in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# Custom application properties
app:
  cors:
    allowed-origins: http://localhost:3000
  elasticsearch:
    index-name: restaurants