spring:
  # ?????? ??
  datasource:
    url: jdbc:mysql://localhost:3306/matzipcurator?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 50
          time_zone: Asia/Seoul  # ?? ??? ??
        default_batch_fetch_size: 100  # ?? ??? ?? ?? ? ?? ?? ???
    open-in-view: false  # OSIV ????

  # Redis ??
  data:
    redis:
      host: localhost
      port: 6379

  # Elasticsearch ??
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 1s
    socket-timeout: 1m

  # Kafka ??
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      group-id: matzipcurator-group
      auto-offset-reset: earliest

# ?? ??
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

# ?? ??
logging:
  level:
    root: INFO
    com.matzipcurator: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.elasticsearch.client.WIRE: TRACE

# JWT ??
jwt:
  secret: your-secret-key-here-should-be-very-long-and-secure
  expiration: 86400000  # 24 hours in milliseconds

# ????? ??
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# ?????? ??? ??
app:
  cors:
    allowed-origins: http://localhost:3000
  elasticsearch:
    index-name: restaurants

# ??? ??
time-zone: Asia/Seoul